### PR TITLE
Fix UB (issue 52)

### PR DESCRIPTION
**Pull request by terrorfisch**
See #52 

I additionally replaced the transmute with a match statement which results in a no-op with minimal optimization but might slow down debug builds. [Tested with godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAM1QDsCBlZAQwBtMQBGAFlJvoCqAZ0wAFAB4gA5AAYppAFZdSrZrVDEArkIKkR7ZATx1KmWugDCqVpoC2tLgGZSZ9ABk8tTADk7AI0xiLgA2UgAHVCFCY1orG3sncMjoug8vX1sAoM5Q/UxDGIYCZmICOLsHTmc8groikoI0n39AkL1i0vKEqvaGpoyskIBKPVRNYmQOKQB6WYBqABFMIWRiPAC55jmqPHY5iDR42iG5uk255ARloTm/VBL0AFIZAEFHgCZHR4BWACFiTBhYgQTQADiGPwWzxeYU0fjmZjscwAYrtMHNHgB2X7QuZ4uYvDGOBZzGSkXH435EkmccmvfFzCzUubvOmE/Ekx7EubOCl47DM3h8lHM75shkAcWZoWFAAlmZi2Vioa9oXhbGFWCi0RjscLZtNGXQAG6BAjnR7BGTaPAAL0wlpkc08RAtVtR7Ed%2BwIV2dtFNxBEpyocyIAH1PFhxEMAHR4gCSIbwRIFirmAHdiMwwptiGNzDHhR8vn9PKxPA7vir2XjYfCqLRtnnbBHzJhxBAKHMbfaTgBaLkCj3orE4%2BkM/G2ZgES7OjHvYJzTG6sc1icMp1cqGOIdokAgF7i9cTzjUwfa9j735H4/495nncXjggCw3288h%2B7y8gBZv2/cT8n33bA/2Pb5AOHfdkVA9dFy3c9IJACUYInZd4MfRDZRQhkw0AzRaABZhLmYPx2DASAIXHddlSLTFqxo1VXjrbZGwIZYCE7EBuyiXs5gHDCdVHYVEKoZtWyjTtKLeOjoSkEZWGkb55AcWR5FQaQACVtHNIQxgmEdPk4eQCGkOQhhGABrEBHEcGMbPshzHNCBSpG4ZTTLU6R5CEEAyRM1SRjgWAkDQDU0TICgDlQML2CCYhOG%2BRwyR2Vg2MDSg/A80g/E8EoAE9pCM0hQtsMwCAAeVoVgCtU0gsCndRL1q/AAQKU0fNq9t8k0NjCvkF1MBcuQVHWLNiDyqwsCygg1lsPqRn4RgWEvHg%2BDoAhhDESRaqUWlVHUEAtB0Ea/B8ijSFQMIjDoDq%2ByZS6CD7dhTVYLcipqa6HAgVwukqFxzH6FpsiSKJPt%2B5QIlBmJAcyVpaQ%2BwoOjKawKmUBG6iRmHBnhpHwZxvoKwGOGRl08ZJi4eTFPc2r1KkI6ZzmTgY0SmMnQgXBCBIedHFpI0YsCbnOBOLSdGMjzzNIKybLsxzZZs5zpDc0gVOG2nvN80h/LM0ggsQEAxgIWFdEi0KwnC5RMHwIhgcWpg2A4VbFs2iQsszbN5pUKnlay2nyp6o3gzmenkEZ5nbLZqx%2BeIQWhjFgLLOs2y5blz3XOp1WvL0DWtbkympHedPPKkOOzJGAMohMbggA).

### CODE REVIEW

**Comment by terrorfisch** [comment]
I additionally defined the representations of CastleRights, Color and Piece because they are used to index into arrays with `get_unchecked` in several places.

**Comment by analog-hors** [comment]
I don't believe that's actually needed because of the indexing, since casting an enum with `as` should be perfectly fine.

**Comment by terrorfisch** [comment]
My fault, I misremembered that the values are guaranteed.

> As in C, discriminant values that are not specified are defined as either 0 (for the first variant) or as one more than the prior variant.

**Comment by jordanbray** [comment]
This looks good to me.  I don't see any reason to avoid merging.  Is this ready to go?

**Comment by terrorfisch** [comment]
If you do not mind the revert commit this can be merged.

**Comment by jordanbray** [comment]
I'll probably do a squash and merge.  I generally prefer that.

**Comment by terrorfisch** [comment]
Then the other question is if you want to keep the `repr(u8)` because the current code does not need it anymore. The only downside is imo that it would be a breaking change to remove it again. The upside is that users can transmute slices without UB.

**Comment by jordanbray** [comment]
I don't really think I care either way.  `repr(u8)` seems like it would _allow_ `mem::transmute`, but I doubt it's that useful in the first place.  Any time I can imagine needing a slice of `Rank` or `File` I feel like I'd intuitively reach for a `BitBoard` instead.

**Comment by analog-hors** [comment]
I don't think there's any point in keeping the `repr`

**Comment by terrorfisch** [comment]
I think one should allow users of this library to transmute if they want to but that is not a strong opinion. @jordanbray You decide and I open up a new squashed PR. Or do you want to do it?

**Pull request merged**
